<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FK8VD7I" ignored="0" name="Test Cases" tests="10" failures="2" timestamp="17 Aug 2023 13:08:01 GMT" time="0.142" errors="0">
  <testcase name="test2" time="0.029" classname="interviewQuestionsSelenium.TestCasesforRerunExamples">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.029" classname="interviewQuestionsSelenium.TestCasesforRerunExamples">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.005" classname="interviewQuestionsSelenium.TestCasesforRerunExamples">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.003" classname="interviewQuestionsSelenium.TestCasesforRerunExamples">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.003" classname="interviewQuestionsSelenium.TestCasesforRerunExamples">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.004" classname="interviewQuestionsSelenium.TestCasesforRerunExamples">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.003" classname="interviewQuestionsSelenium.TestCasesforRerunExamples">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.003" classname="interviewQuestionsSelenium.TestCasesforRerunExamples">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.002" classname="interviewQuestionsSelenium.TestCasesforRerunExamples">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at interviewQuestionsSelenium.TestCasesforRerunExamples.test1(TestCasesforRerunExamples.java:10)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.003" classname="interviewQuestionsSelenium.TestCasesforRerunExamples">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at interviewQuestionsSelenium.TestCasesforRerunExamples.test2(TestCasesforRerunExamples.java:15)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test Cases -->
